### ISSUE TITLE
Docker instance does not update git repo when started.

### ISSUE THREAD

**Issue by wroscoe** [wroscoe/donkey#82]
People who use the docker image to start the server don't use an updated version of the git repo. The repo can be updated manually by running 
``` 
bash start-server.sh -d
```
and then running the following inside the docker instance.
```
git pull origin master
```
but it would be better if this updated automatically, assuming we can keep the master branch free of conflicts.  @yconst  do you know how to do this.

**Comment by yconst** [comment]
I think if one does a `git pull` and then normally start the server, i.e. `./start-server.sh` , it should update the tree inside the image automatically (the only drawback being that it runs `pip install` again). I tend to believe that this should be the standard way of doing things (i.e. the docker tree always mirrors the local tree), otherwise there is the risk of conflicts as you mentioned.

**Comment by yconst** [comment]
Actually the way the Dockerfile is configured it should only trigger a `pip install` if setup.py changes.

**Comment by yconst** [comment]
Or we could completely switch to using the `-v` flag in the startup script (and lose a bit of portability along the way)

**Comment by binary-bard** [comment]
Are there any downsides to mapping the directory (just like mydonkey) to docker image? That way, one can do git pull without needing to refresh/rebuild docker image.

**Comment by tizianofiorenzani** [comment]
Guys, for people like me that have never used docker before, would be great to have it mentioned at least  in the readme

**Comment by wroscoe** [comment]
Awesome feedback. Can you make a pull request?

-Will

**Comment by wroscoe** [comment]
The new version doesn't require docker as everything is run on the pi.
